alfabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
RUTA_ROTOR1 = "data/Rotor1.txt"
RUTA_ROTOR2 = "data/Rotor2.txt"
RUTA_ROTOR3 = "data/Rotor3.txt"
RUTA_MISSATGE = "data/Missatge.txt"
RUTA_MISSATGE_DESXIFRAT = "output/desxifrat.txt"